POST http://localhost:3003/api/blogs
Content-Type:application/json

{
  "title": "DogsAndCats blog",
  "author": "Aku Tuhkanen",
  "url": "http://Dogandcatblog.fi",
  "likes": 2,
  "userId": "62c573b8ca32c0be62830afa"
}