POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrdXR1aCIsImlkIjoiNjJjNjdiYzZlNmU1OWM1OWIxYTU5OWZjIiwiaWF0IjoxNjU3MTc0OTg3fQ.kNzLygdibGm9C8LxikF0YJL7NFp9r9gmNLEI-wuk3YU

{
  "title": "Orava blog",
  "author": "Aku Tuhkanen",
  "url": "http://blog.orava.fi",
  "likes": 55
}